#ifndef IR_LINE_H_
#define IR_LINE_H_

#include "driver/gpio.h"
#include "sdkconfig.h"
#include "soc/gpio_reg.h"


#define IR_LINE_IS_BLACK

#define INFRA_RED_LEFT_GPIO  GPIO_NUM_15
#define INFRA_RED_CENTER_LEFT_GPIO  GPIO_NUM_16
#define INFRA_RED_MIDDLE_GPIO  GPIO_NUM_17
#define INFRA_RED_CENTER_RIGHT_GPIO  GPIO_NUM_18
#define INFRA_RED_RIGHT_GPIO GPIO_NUM_8

#define INFRA_RED_GPIO_PINS_MASK ((uint64_t)((1ULL << INFRA_RED_LEFT_GPIO) | (1ULL << INFRA_RED_CENTER_LEFT_GPIO) | (1ULL << INFRA_RED_MIDDLE_GPIO) | (1ULL << INFRA_RED_CENTER_RIGHT_GPIO) | (1ULL << INFRA_RED_RIGHT_GPIO)))

#ifdef IR_LINE_IS_BLACK
#define IR_LINE_VERY_VERY_LEFT ~(1ULL << INFRA_RED_LEFT_GPIO)
#define IR_LINE_VERY_LEFT ~((1ULL << INFRA_RED_LEFT_GPIO) | (1ULL << INFRA_RED_CENTER_LEFT_GPIO))
#define IR_LINE_LEFT ~(1ULL << INFRA_RED_CENTER_LEFT_GPIO)
#define IR_LINE_LEFT_MIDDLE ~((1ULL << INFRA_RED_CENTER_LEFT_GPIO) | (1ULL << INFRA_RED_MIDDLE_GPIO))
#define IR_LINE_MIDDLE ~(1ULL << INFRA_RED_MIDDLE_GPIO)
#define IR_LINE_RIGHT_MIDDLE ~((1ULL << INFRA_RED_MIDDLE_GPIO) | (1ULL << INFRA_RED_CENTER_RIGHT_GPIO))
#define IR_LINE_RIGHT ~(1ULL << INFRA_RED_CENTER_RIGHT_GPIO)
#define IR_LINE_VERY_RIGHT ~((1ULL << INFRA_RED_CENTER_RIGHT_GPIO) | (1ULL << INFRA_RED_RIGHT_GPIO))
#define IR_LINE_VERY_VERY_RIGHT ~(1ULL << INFRA_RED_RIGHT_GPIO)
#define INFRA_RED_OUT_GPIO_MASK ~INFRA_RED_GPIO_PINS_MASK
#else
#define IR_LINE_VERY_VERY_LEFT (1ULL << INFRA_RED_LEFT_GPIO)
#define IR_LINE_VERY_LEFT ((1ULL << INFRA_RED_LEFT_GPIO) | (1ULL << INFRA_RED_CENTER_LEFT_GPIO))
#define IR_LINE_LEFT (1ULL << INFRA_RED_CENTER_LEFT_GPIO)
#define IR_LINE_LEFT_MIDDLE ((1ULL << INFRA_RED_CENTER_LEFT_GPIO) | (1ULL << INFRA_RED_MIDDLE_GPIO))
#define IR_LINE_MIDDLE (1ULL << INFRA_RED_MIDDLE_GPIO)
#define IR_LINE_RIGHT_MIDDLE ((1ULL << INFRA_RED_MIDDLE_GPIO) | (1ULL << INFRA_RED_CENTER_RIGHT_GPIO))
#define IR_LINE_RIGHT (1ULL << INFRA_RED_CENTER_RIGHT_GPIO)
#define IR_LINE_VERY_RIGHT ((1ULL << INFRA_RED_CENTER_RIGHT_GPIO) | (1ULL << INFRA_RED_RIGHT_GPIO))
#define IR_LINE_VERY_VERY_RIGHT (1ULL << INFRA_RED_RIGHT_GPIO)
#define INFRA_RED_OUT_GPIO_MASK INFRA_RED_GPIO_PINS_MASK
#endif

#endif //IR_LINE_H_